---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "transmission.fullname" . }}-secrets
  namespace: {{ include "transmission.namespace" . }}
data:
  transmission-password: {{ ((.Values).secrets).password | default "changeme" | b64enc }}
