apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    name: http
    port: 9091
  - protocol: TCP
    name: tcp
    port: 51413
  - protocol: UDP
    name: udp
    port: 51413
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
