# Default values for transmission.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lscr.io/linuxserver/transmission
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

configMap:
  tz: "Europe/Rome"
  transmissionWebHome: "/ui/flood-for-transmission"
  puid: "1000"
  pgid: "1000"
  tz: UTC
  user: admin

ui:
  darkMode: "enabled"
  switchColors: "true"
  notation24H: "true"
  wrapHeader: "true"
  commonPath: ""
  columns: "[{ label: \"Name\", width: 400, enabled: true }, { label: \"Progress\", width: 600 }, { label: \"Ratio\", width: 0, enabled: false }]"
  sortColumn: "Ratio"
  sortDirection: "asc"
  showDiskUsage: "true"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  # -- Enable Ingress Creation
  enabled: true
  ingresses:
    - className: ""
      # -- Annotations on the ingress object.
      annotations: {}
      labels: {}
      # -- The hostname that should be used.
      hosts:
        - host: transmission.casa-titi.com
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: transmission
                  port:
                    number: 9091
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /transmission/web
#    port: http
#readinessProbe:
#  httpGet:
#    path: /transmission/web
#    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
